CC = gcc
CFLAGS = -Wall -Wextra -std=c11
TARGET = salesReport
SRC = 348salesFAlexanderWichern.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)